import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Layout from "@/components/layout";
import { Button } from "@/components/ui/button";

export default function Home() {
    return (
        <>
            <Head>
                <title>PO-in</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="flex p-4">
                    <Button onClick={() => void signIn()}>Sign in</Button>
                </div>
                <div className="flex max-h-full flex-col space-y-2 overflow-y-auto px-2 pb-12 pt-2">
                    <AuthShowcase />
                </div>
            </Layout>
        </>
    );
}

function AuthShowcase() {
    const { data: sessionData } = useSession();
    return (
        <Card className="min-w-full max-w-full">
            <CardHeader>
                <CardTitle className="capitalize">
                    {sessionData?.user
                        ? `Hello, ${sessionData.user.name}`
                        : "Login Please !"}
                </CardTitle>
            </CardHeader>
            <CardContent>Lorem ipsum dolor sit amet</CardContent>
        </Card>
    );
}
